
package soap.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.0
 * Wed May 17 16:12:31 IST 2023
 * Generated source version: 3.6.0
 */

@XmlRootElement(name = "storeMarksResponse", namespace = "http://webservice.soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "storeMarksResponse", namespace = "http://webservice.soap/")

public class StoreMarksResponse {


}

